// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQm_fSRl27xb__jl873L3Ejts65yI7wc',
    appId: '1:302359071237:web:5c98acc949c48687db6a6c',
    messagingSenderId: '302359071237',
    projectId: 'meditate---app',
    authDomain: 'meditate---app.firebaseapp.com',
    storageBucket: 'meditate---app.appspot.com',
    measurementId: 'G-KQ3WPMBSSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapt9s-9g9ncilELsi-o7nikIprr6_fw8',
    appId: '1:302359071237:android:4d27cafe3659d9eddb6a6c',
    messagingSenderId: '302359071237',
    projectId: 'meditate---app',
    storageBucket: 'meditate---app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoKoOod1crmzZstQyLdaR-dwF_1hjjb1s',
    appId: '1:302359071237:ios:e9f0bd3ebda55e26db6a6c',
    messagingSenderId: '302359071237',
    projectId: 'meditate---app',
    storageBucket: 'meditate---app.appspot.com',
    iosClientId: '302359071237-baidh2cbv9i7prbhu9d13o314jjg6cia.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoKoOod1crmzZstQyLdaR-dwF_1hjjb1s',
    appId: '1:302359071237:ios:e9f0bd3ebda55e26db6a6c',
    messagingSenderId: '302359071237',
    projectId: 'meditate---app',
    storageBucket: 'meditate---app.appspot.com',
    iosClientId: '302359071237-baidh2cbv9i7prbhu9d13o314jjg6cia.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditationApp',
  );
}
