// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATC4BjRaO5JVSGwnQLuzFVCxYGEokDCkI',
    appId: '1:928203370994:web:434a8778b8164f44353b6b',
    messagingSenderId: '928203370994',
    projectId: 'meditate-app-e19c8',
    authDomain: 'meditate-app-e19c8.firebaseapp.com',
    storageBucket: 'meditate-app-e19c8.appspot.com',
    measurementId: 'G-SWG713JHD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1AEjbQmAWPSU98eiRA1DzJ-mMLpQwkXM',
    appId: '1:928203370994:android:8713ccfb1d13b6b4353b6b',
    messagingSenderId: '928203370994',
    projectId: 'meditate-app-e19c8',
    storageBucket: 'meditate-app-e19c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHOsquZThVdKqdexNHSwC5ip5oGP0QHrY',
    appId: '1:928203370994:ios:0bb9b0ab8d28d0c8353b6b',
    messagingSenderId: '928203370994',
    projectId: 'meditate-app-e19c8',
    storageBucket: 'meditate-app-e19c8.appspot.com',
    iosClientId: '928203370994-qcmeack1ek7bghso954efrobtlbuqtmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHOsquZThVdKqdexNHSwC5ip5oGP0QHrY',
    appId: '1:928203370994:ios:0bb9b0ab8d28d0c8353b6b',
    messagingSenderId: '928203370994',
    projectId: 'meditate-app-e19c8',
    storageBucket: 'meditate-app-e19c8.appspot.com',
    iosClientId: '928203370994-qcmeack1ek7bghso954efrobtlbuqtmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditationApp',
  );
}
